config/routes.rb
Rails.application.routes.draw do
  resources :planes
  # only: [:index, :show, :new, :create, :edit, :update ]

  # get 'planes', to: 'planes#index'
  # get 'planes/:id', to: 'planes#show'
  # get 'planes/new', to: 'planes#new'
  # post 'planes', to: 'planes#create'
  # get 'planes/:id/edit', to: 'planes#edit'
  # patch 'planes/:id', to: 'planes#update'
  # delete 'planes/:id', to: 'planes#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plane.rb
class Plane < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  before_action :set_plane, only: [:show, :edit, :update, :destroy]

  def index
    @planes = Plane.all
  end

  def show
  end

  def new
    @plane = Plane.new

  end

  def create
    plane = Plane.create(plane_params)
    redirect_to plane_path(plane)
  end

  def edit
  end

  def update
    @plane.update(plane_params)
    redirect_to plane_path(@plane)

  end

  def destroy
    @plane.destroy
    redirect_to planes_path
  end

  private

  def plane_params
    params.require(:plane).permit(:name, :origin, :stars)
  end

  def set_plane
    @plane = Plane.find(params["id"])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/planes/_form.html.erb
<h1>Planes supermarket</h1>
<%= form_for@plane do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :origin %>
  <%= f.label :stars %>
  <%= f.number_field :stars %>
  <%= f.submit %>
<% end %>

app/views/planes/edit.html.erb
<%= render partial: 'form' %>

app/views/planes/index.html.erb
<h1>Planes supermarket</h1>
<p><%= link_to "Add new plane", new_plane_path %></p>
<% @planes.each do |plane| %>
  <h2><%= plane.name %></h2>
  <p><%= plane.origin %></p>
  <p><%= "*" * plane.stars %></p>
  <p><%= link_to "See more", plane_path(plane) %>
    <%= link_to "Update", edit_plane_path(plane) %>
  </p>
<% end %>

app/views/planes/new.html.erb
<%= render partial: 'form' %>

app/views/planes/show.html.erb
<h1>Planes supermarket</h1>
  <h2><%= @plane.name %></h2>
  <p><%= @plane.origin %></p>
  <p><%= "*" * @plane.stars %></p>
  <p><%= link_to "Update", edit_plane_path(@plane) %>
    <%= link_to "Back to index", planes_path %>
    <%= link_to "Delete", plane_path(@plane),
    method: :delete,
    data: { confirm: "Are you sure?" } %>
  </p>